# Global schema settings
schema_version: 1.0
app_name: CRAPP

app:
  name: "CRAPP - Cognitive Reporting Application"
  environment: "development"  # Options: development, production, testing
  questions_file: "questions.yaml"

database:
  driver: postgres
  #url: stored in ENV

server:
  host: "0.0.0.0"
  port: 5000

logging:
  directory: logs
  level: "warn"      # Options: debug, info, warn, error
  format: "json"     # Options: json, console

reminders:
  frequency: daily
  times: [20:00]  # 8pm
  cutoff_time: 10:00  # Can submit yesterday's data until 10am

jwt:
  #secret: stored in ENV
  expires: 15 # JWT token expiration in minutes
  refresh_expires: 5 # Refresh token expiration in days

pwa:
  enabled: true
  #vapid_public_key: stored in ENV
  #vapid_private_key: stored in ENV

tls:
  enabled: true
  #cert_file: stored in ENV
  #key_file: stored in ENV
  http_port: 8080  # Optional port for HTTP redirect

# Email configuration
email:
  enabled: true
  smtp_host: "smtp.mailersend.net"
  smtp_port: 587
  #smtp_username: stored in ENV
  #smtp_password: stored in ENV
  from_email: "MS_MOJ1mU@trial-vz9dlemej3n4kj50.mlsender.net"
  from_name: "CRAPP Notification"
  app_url: "https://archania.net:5000"  # Base URL for links in emails