services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: crapp
    hostname: app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" # Internal port where app listens
    environment:
      # Place app-specific environment variables here
      CRAPP_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=require"
      CRAPP_JWT_SECRET: ${JWT_SECRET}
      CRAPP_PWA_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      CRAPP_PWA_VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      CRAPP_EMAIL_SMTP_USERNAME: ${SMTP_USERNAME}
      CRAPP_EMAIL_SMTP_PASSWORD: ${SMTP_PASSWORD}
      CRAPP_SERVER_PORT: ${SERVER_PORT}
      TZ: "America/New_York"
    volumes:
      - crapp-logs:/app/logs
    networks:
      - crapp-network

  db:
    build:
      context: ../
      dockerfile: docker/Dockerfile.db
    container_name: crapp-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crapp-network

networks:
  crapp-network:
    driver: bridge

volumes:
  postgres-data:
  crapp-logs: